version: 1.0
stages:
  - install
  - build
  - test
steps:
  clone:
    description: Cloning repository...
    type: git-clone
    stage: install
    repo: vallerance/react-orcus
    revision: ${{CF_BRANCH}}
  install:
    title: Build react-orcus docker image
    type: build
    stage: install
    image_name: react-orcus
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}
    working_directory: ${{clone}}
    registry: github-container-registry-vallerance
    no_cf_cache: true
  build:
    title: Building library
    type: build
    stage: build
    image_name: react-orcus-build
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}
    working_directory: ${{clone}}
    dockerfile: codefresh/build.Dockerfile
    build_arguments:
      - VERSION=${{CF_BRANCH_TAG_NORMALIZED}}
    registry: github-container-registry-vallerance
  build-cache:
    title: Caching build artifacts
    stage: build
    image: ${{build}}
    working_directory: IMAGE_WORK_DIR
    commands:
      - cp -r ./dist /codefresh/volume/dist
  build-test:
    title: Building test image
    type: build
    stage: test
    image_name: react-orcus-test
    tag: ${{CF_BRANCH_TAG_NORMALIZED}}
    working_directory: ${{clone}}
    dockerfile: codefresh/test.Dockerfile
    registry: github-container-registry-vallerance
  test:
    title: Running tests
    stage: test
    image: ${{build-test}}
    working_directory: IMAGE_WORK_DIR
    commands:
      - cp -r /codefresh/volume/dist ./dist
      - npm test
